### PR TITLE
Temp fix for 0.7.0 path and quote issue on windows

### PR DESCRIPTION
**Pull request by cgarz**
As per the request from @zyronix on the discord I've made it a PR.

However it's quite an ugly fix and has not been well tested. I only fixed just enough to get the client to run on windows for a standard bruteforce attack with nothing else such as other files or pre processing. So there are probably other paths that have yet to be fixed.

It creates a global SEP variable that holds the OS specific path separator and uses that in place of hard coded forward slashes.
And it uses double quotes in place of single quotes in the argument building as cmd doesn't support single.
It also switches the hashcat separator char argument to the literal characters `0x09` as hashcat supports that natively now. Windows cmd was choking on the tab char.

In time I may attempt a proper fix with pathlib and switching to building an argument list instead of an argument string containing hardcoded quotes but for now this at least has it running on windows.

### CODE REVIEW

**Comment by netsecprogrammer** [comment]
I've attempted these changes for 0.7 on my windows server and they are incomplete.  The single quote issue affects more files than what are modified in this pull request.  For my case, the part that was broken was single quotes around the dictionary name used in a dictionary attack.

**Comment by netsecprogrammer** [comment]
Hi @s3inlc,
I pulled down the latest master and I can confirm that everything works now.

**Comment by s3inlc** [comment]
Thanks for testing and your feedback @netsecprogrammer 

I propose that this PR could then be closed.

**Comment by zyronix** [comment]
@cgarz thanks for your contribution. I used it to verify my changes. Thanks :)

**Comment by cgarz** [comment]
Ah that's excellent news! No probs happy to help :)

**Pull request closed without merging**
