### PR TITLE
Adding test framework, fix for window paths and fix for preprocessors

### PR DESCRIPTION
**Pull request by zyronix**
Sorry for the large pull request, but everything is connected together. This changes fixes the following:

* Agent working again on Windows, all paths have been converted to Pathlib.Path and using the correct quoting of arguments.
* 7z wordlist not extracting correctly on Windows.
* preprocessor not working correctly on both Windows and Linux.

Also it adds a testframework. With some limitations:
* Only works with apiv2
* No support yet for Github Actions
* Windows tests only run on a real windows platform, due to required support of some OpenCL device.

### CODE REVIEW

**Comment by fsacer** [comment]
hoping this gets merged asap so my cracking rigs can get up and running again

**Comment by miketweaver** [comment]
```
[2023-03-01 13:34:15,436] [INFO ] Client is up-to-date!
[2023-03-01 13:34:15,436] [INFO ] Got cracker binary type hashcat
[2023-03-01 13:34:15,437] [DEBUG] CALL: C:\Users\user\Downloads\hashes\crackers\1\hashcat.exe --version
[2023-03-01 13:34:15,443] [DEBUG] {'action': 'getChunk', 'token': '**REDACTED**', 'taskId': 16}
[2023-03-01 13:34:15,504] [DEBUG] https://**REDACTED**:443 "POST /api/server.php HTTP/1.1" 200 None
[2023-03-01 13:34:15,504] [DEBUG] b'{"action":"getChunk","response":"SUCCESS","status":"benchmark"}'
[2023-03-01 13:34:15,504] [INFO ] Benchmark task...
[2023-03-01 13:34:15,505] [DEBUG] CALL: "hashcat.exe" --machine-readable --quiet --progress-only --restore-disable --potfile-disable --session=hashtopolis -p 0x09  "C:\Users\user\Downloads\hashes\hashlists\27" "C:\Users\user\Downloads\hashes\files\rockyou.txt"   --hash-type=0  -o "C:\Users\user\Downloads\hashes\hashlists\27.out"
[2023-03-01 13:34:15,521] [ERROR] Error during speed benchmark, return code: 4294967295 Output:
[2023-03-01 13:34:15,521] [DEBUG] {'action': 'clientError', 'token': '**REDACTED**', 'taskId': 16, 'chunkId': None, 'message': 'Speed benchmark failed!'}
[2023-03-01 13:34:15,592] [DEBUG] https://**REDACTED**:443 "POST /api/server.php HTTP/1.1" 200 45
[2023-03-01 13:34:15,593] [DEBUG] b'{"action":"clientError","response":"SUCCESS"}'
[2023-03-01 13:34:19,144] [INFO ] Exiting...
```

I think the issue is this: `-p 0x09 `

**Comment by zyronix** [comment]
Ah indeed, the hex seperator was added very recently indeed. I'll revert back that change and give people a bit more time for that change :).

**Comment by zyronix** [comment]
Should be fixed in [bd4e4dc](https://github.com/hashtopolis/agent-python/pull/36/commits/bd4e4dcaf93353170497ac477bb8c75b0875bcad)

**Comment by zyronix** [comment]
For sure, I have created an issue for this. [#server](https://github.com/hashtopolis/server/issues/864)
But lets leave that out for now and get this one merged.

**Review by s3inlc — APPROVED** [review]

**Pull request merged**
